name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: CMake
        run: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SUPPRESS_DEVELOPER_WARNINGS=TRUE -DCMAKE_CXX_FLAGS="-w"
      - name: Make all targets
        run: make all

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy cmake ninja-build

      - name: Run Clang-Tidy
        run: clang-tidy -p build $(find . -name '*.cpp' -or -name '*.h')

      - name: UT for BtsApplication
        run: make BtsApplicationUT

      - name: run BTS ut
        run: ./BTS/Tests/Application/BtsApplicationUT

      - name: UT for COMMON
        run: make COMMON_UT

      - name: UT for UeApplication
        run: make UeApplicationUT