name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
        
    steps:
    - uses: actions/checkout@v2
    - name: Remove existing Qt directory
      run: rm -rf ~/Qt && rm -rf /home/runner/work/Nokia-PK-2025/Qt/

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: cmake
      run: cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .
    - name: make all targets
      run: make all


    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang-tidy cmake ninja-build

    - name: Configure CMake
      run: |
        cmake -S ./UE -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja

    - name: Run Clang-Tidy
      run: clang-tidy -p build $(find . -name '*.cpp' -or -name '*.h')

    - name: UT for BtsApplication
      run: make BtsApplicationUT 

    - name: run BTS ut
      run: ./BTS/Tests/Application/BtsApplicationUT

    - name: UT for COMMON
      run: make COMMON_UT

    - name: UT for UeApplication
      run: make UeApplicationUT